config/routes.rb
Bookmakr::Application.routes.draw do

  get 'users/autocomplete_user_username'
  get 'users/autocomplete_tag_title'

  resources :bookmarks
  resources :tags
  
  resources :lists do
    get :share, :on=>:member
  end
  
  resources :shares 
  
  resources :users do
    get :bookmarks, :on=>:member
    get :autocomplete_tag_title_users
    get :autocomplete_user_username_users
    resources :tags, :only => :show
  end
  
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "devise/sessions"}, :path=>"account"

  root :to => 'bookmarks#index'
end

app/models/list.rb
class List < ActiveRecord::Base
  
  belongs_to :user
  has_many :shares
  has_and_belongs_to_many :bookmarks
  
  scope :public, where('public'=>true)
  
  def self.users_lists(user_id)
    where("user_id=?",user_id)
  end
  
  def self.public_lists
    where("public=?",true)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
protected
  before_filter :get_list, :only=>[:show, :edit, :update, :destroy, :share, :bookmarks]

public  
  def get_list
    @list = List.find(params[:id])
  end

  def index
    if signed_in?
      @lists = current_user.lists
    else
      redirect_to root_path
    end
  end

  def show
    if signed_in? && current_user.lists.index(@list)
      @bookmarks = @list.bookmarks.paginate(:page => params[:page])
      @public_only = false
    elsif @list.public
      @bookmarks = @list.bookmarks.paginate(:page => params[:page])
      @public_only = true
    else
      redirect_to root_path
    end
      
    if @boomarks
    	@tags = @bookmarks.collect{|b| b.tags}.flatten.uniq.sort{ |a,b| a.bookmarks.count <=> b.bookmarks.count}
    	
    end  
  end
 
  def destroy
    @list.bookmarks.each do |b|
      #if a bookmark is only in the list to destroy and the users default_list it can be destroyed
      if(b.lists.count==2)
        b.delete
      else
        b.lists.delete(@list)
        b.save
      end
    end
    
    @list.shares.each do |s|
      s.destroy
    end
    @list.destroy
    
    redirect_to lists_path
  end

  def create
    current_user.lists.create(params[:list])
    
    redirect_to lists_path
  end

  def edit
  end

  def update
    @list.update_attributes(params[:list])
    
    redirect_to lists_path
  end

  def new
    @list = List.new
  end
  
  def share
    @share = @list.shares.new
    @users = User.all_users_except(current_user)
    render :template=>'shares/new'
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <div><%= f.label :title%><%=f.text_field :title%></div>
  <div><%= f.label :description%><%=f.text_area :description%></div>
  <div><%= f.label :public%><%= f.check_box :public%></div>
  <div><%= f.submit%></div>
<%end%>

app/views/lists/_list.html.erb
<% if list != list.user.default_list %>
  <div class="item_wrapper">
    <div class="item">
      <span class="item_title"><%= list.title %></span>
      <p>public: <%= list.public %></p>
      <%if list.shares.count > 0 %>
        <div class="shares">
          <strong><%= t(:shares) %></strong>
          <%= render list.shares %> 
        </div>
      <%end%>
      <div class="item_links">
        <%= link_to t(:edit), edit_list_path(list) %>
        <%= link_to t(:share), share_list_path(list) %>
        <%= link_to(t(:delete),  list, :method => :delete, :confirm => "Are you sure?") %>
        <%= link_to t(:show_bookmarks), list_path(list) %>
      </div>
    </div>
  </div>
<%end%>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/edit.html.erb
<%= render "form" %>

app/views/lists/index.html.erb
<div id="list_wrapper">
  <div id="lists">
    <%= render @lists %>
  </div>
</div>

app/views/lists/new.html.erb
<%= render "form" %>

app/views/lists/share.html.erb
<%= form_for(@share) do |f| %>
<div id="errors">
  <%= f.error_messages %>

  <ul>
      <% @share.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
  </ul>

  
</div>
  <div><%= f.label :write%><%=f.check_box :write%></div>
  <div>
  <%= f.label :users%>
  <%= text_field_tag "user",'', :'data-autocomplete' => users_autocomplete_user_username_path, :'data-delimiter' => ',' %>
  </div>
  <div><%= hidden_field_tag  'list_id', @list.id %></div>  
  <div><%= f.submit%></div>
<%end%>

app/views/lists/show.html.erb
<%= render :partial=>"bookmarks/bookmarks_with_tags", :locals=>{:public_only => @public_only, :bookmarks=>@bookmarks, :tags=>@tags} %>

app/views/lists/update.html.erb
<h1>Lists#update</h1>
<p>Find me in app/views/lists/update.html.erb</p>