config/routes.rb
Bookmakr::Application.routes.draw do

  get 'users/autocomplete_user_username'
  get 'users/autocomplete_tag_title'

  resources :bookmarks
  resources :tags
  
  resources :lists do
    get :share, :on=>:member
  end
  
  resources :shares 
  
  resources :users do
    get :bookmarks, :on=>:member
    get :autocomplete_tag_title_users
    get :autocomplete_user_username_users
    resources :tags, :only => :show
  end
  
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "devise/sessions"}, :path=>"account"

  root :to => 'bookmarks#index'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :lists
  
  default_scope order('bookmarks.created_at DESC')
  scope :public, joins(:lists).where('lists.public'=>true).includes(:lists).where('lists.public'=>true)
  
  self.per_page = 10
  
  #returns all public bookmarks tagged with tag
  def self.find_public_bookmarks_with_tag(tag)
    public_bookmarks.joins(:tags).where(:tags => {:title => tag.title})
  end
  
  def self.find_public_bookmarks_of_user_with_tag(user, tag)
     Bookmark.includes(:lists).where("lists.user_id=? AND lists.public = ?", user.id, true).joins(:tags).where(:tags => {:title => tag.title}).order('bookmarks.created_at DESC')
  end
  
  def self.find_bookmarks_of_user_with_tag(user, tag)
     Bookmark.includes(:lists).where("lists.user_id=?", user.id).joins(:tags).where(:tags => {:title => tag.title}).order('bookmarks.created_at DESC')
  end
  
  def self.of_user(user)
    Bookmark.includes(:lists).where(:lists=>{:user_id=>user.id})
  end
  
  def self.shared_bookmarks_of_user(user)
    list_ids = user.shares.map{|s| s.list}.flatten.map{|l| l.id}.flatten
    Bookmark.includes(:lists).where(:lists=>{:id => list_ids})
  end
  
  def self.public_bookmarks_of_user(user)
    of_user(user).joins(:lists).where(:lists=>{:public=>true})
  end
  
  def self.own_and_shared_bookmarks_of_user(user)
    list_ids = user.shares.map{|s| s.list}.flatten.map{|l| l.id}.flatten
    Bookmark.includes(:lists).where("lists.user_id= ? or lists.id IN (?)",user.id,list_ids)
  end
  
  #parses the tag string and creates an array of tags
  def self.parse_tag_string(tagstring)
    tags = tagstring.split(',') 
    tags = tags.map do |t|
      t = t.strip
      t = t.downcase
    end
    tags.uniq!
    return tags
  end
  
  def self.has_user_write_share_on_bookmark(user, bookmark)
    list_ids = user.shares.find_all{|s| s.write == true}.map{|s| s.list}.flatten.map{|l| l.id}.flatten
    bookmark_list_ids = bookmark.lists.map{|l| l.id}.flatten
    Bookmark.joins(:lists).where("lists.id IN (?) AND lists.id IN(?)",list_ids, bookmark_list_ids)
  end
  
  def set_tags(user, newtags)
    if !newtags.nil?
      newtags.each do |t|
        t = t.strip
        t = t.downcase
        
        tag = Tag.find_by_title(t)
        
        if tag.nil?
          tag = user.tags.create(:title=>t)
        else
          if !Tag.find_user_tag_by_title(user,tag)
            user.tags << tag
          end
        end
        tags << tag
      end
    end 
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :username
  
  belongs_to :default_list, :foreign_key=>:default_list_id, :class_name=>'List'
  has_and_belongs_to_many :tags

  
  has_many :lists
  has_many :bookmarks, :through => :lists
  has_many :shares
  

  
  def writable_lists
    w_lists = lists.to_ary | shares.select{|s| s.write == true}.collect{|s| s.list}.flatten.uniq
    w_lists.delete(default_list)
    return w_lists
  end
  
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :username, :presence => true 
  validates_uniqueness_of :username
  validates :email, :presence => true
  
  validates :password, :presence => true
  validates :password_confirmation, :presence => true
  validates_confirmation_of :password

  
  def bookmarks_with_tag(tag)
    Bookmark.find_bookmarks_of_user_with_tag(self,tag)
  end
  
  def public_bookmarks_with_tag(tag)
    Bookmark.find_public_bookmarks_of_user_with_tag(self,tag)
  end

  def public_bookmarks
    Bookmark.public_bookmarks_of_user(self)
  end
  
  def own_and_shared_bookmarks
    Bookmark.own_and_shared_bookmarks_of_user(self)
  end
  
  def shared_writable_bookmarks
    Bookmark.shared_writable_bookmarks_of_user()
  end
  
  def is_bookmark_write_shared(bookmark)
    Bookmark.has_user_write_share_on_bookmark(self, bookmark)
  end
  
  def self.all_users_except(user)
    where(:id_not=>user.id).order("username")
  end
  
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  public
  #shows all public bookmarks and their tags
  def index
    @bookmarks = Bookmark.public.paginate(:page => params[:page])
    @public_only = true
    @tags = @bookmarks.collect{|b| b.tags}.flatten.uniq.sort{ |a,b| a.bookmarks.count <=> b.bookmarks.count}
  end

  def show
  end
  
  def destroy
    @bookmark.destroy
    
    #redirect to the page the request came from
    redirect_to(request.env["HTTP_REFERER"])
  end

  def create

    if params[:bookmark][:list_ids] 
      params[:bookmark][:list_ids] << current_user.default_list.id
    else
      params[:bookmark][:list_ids] = current_user.default_list.id

    end
    
    b = Bookmark.new(params[:bookmark])

    tags = Bookmark.parse_tag_string(params[:tagstring])	
    
    b.set_tags(current_user, tags)
    
    b.save!
    
    #redirects to the users bookmark page
    redirect_to bookmarks_user_path(current_user)
  end

  def edit
    @tags = @bookmark.tags.map { |t| t.title }.join(', ')

    #stores all lists, the user is allowed to write in
    #those are his/her own lists, and all the lists the shared
    #with the write flag true
    @available_lists = current_user.writable_lists
  end

  def update
    @bookmark.tags.clear  
    foreign_lists = Array.new
    tags = Bookmark.parse_tag_string(params[:tagstring])	
    @bookmark.set_tags(current_user, tags)    
    
	@bookmark.lists.each do |l|
	  if l.user_id != current_user.id
        foreign_lists << l
	  end
	end
    @bookmark.update_attributes(params[:bookmark])
	foreign_lists.each do |l|
	  @bookmark.lists << l
	end
    redirect_to bookmarks_user_path(current_user)
  end

  def new
    @bookmark = Bookmark.new

    #stores all lists, the user is allowed to write in
    #those are his/her own lists, and all the lists the shared
    #with the write flag true
    @available_lists = current_user.writable_lists
  end
  
  
  protected
  
  before_filter :get_bookmark, :only=>[:show, :edit, :update, :destroy]
  
  before_filter :authenticate_user!, :except=>[:index]
  
  before_filter :is_user_allowed_to, :except=>[:index, :new, :create, :destroy]
  
  before_filter :add_default_list_to_params, :only=>[:create, :update]
  
  #gets the bookmark defined by the id in the params-field
  def get_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
  
  #if the user is not allowed to do the current action,
  #a redirection to the root is done
  def is_user_allowed_to
    if !@bookmark.lists.find_all{|l| l.user == current_user}.empty?
      return
    end
    else if(!current_user.is_bookmark_write_shared(@bookmark).empty?)
	return  
    end

    redirect_to root_path
  end
  
  def add_default_list_to_params
    if params[:bookmark][:list_ids] 
      params[:bookmark][:list_ids] << current_user.default_list.id
    else
      params[:bookmark][:list_ids] = current_user.default_list.id
    end
  end

end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
  def user_allowed_to_edit(user, bookmark)
    allowed = false
    if(!current_user.bookmarks.index(bookmark).nil?)
      allowed = true
    else
      write_shares = current_user.shares.find_all{|s| s.write == true}
      write_shares.each do |s|
        if bookmark.lists.index(s.list)
          allowed = true
        end
      end
    end
    return allowed
  end
  
end

app/views/bookmarks/_bookmark.html.erb
<div class="item_wrapper"%>
  <div class="item">
    <span class="item_title"><%= bookmark.title %></span>&nbsp;<span class="item_url"><%= link_to bookmark.url, bookmark.url%></span>, 
    <span class="user">by&nbsp;<%= link_to bookmark.lists.first.user.username, bookmarks_user_path(bookmark.lists.first.user) %>,&nbsp;</span>
    <span class="date"><%= l bookmark.created_at, :format=>:short%></span>
    <div class="lists"> 
      <strong>Lists:</strong>
        <% bookmark.lists.each do |l|%>
          <% if l != l.user.default_list %>
            <%= link_to l.title, list_path(l) %><%= (bookmark.lists.last != l) ? ", " : ""%>
          <%end%>
        <%end%>	
    </div>
    <div class="tags">
      <% if !bookmark.tags.empty? %>
        <strong>[</strong>
        <% bookmark.tags.each do |t|%>
          <% if public_only == true %>
            <%= link_to t.title, tag_path(t) %><%= (bookmark.tags.last != t) ? " ," : ""%>
          <%else%>
            <%= link_to t.title, user_tag_path(current_user, t) %><%= (bookmark.tags.last != t) ? " ," : ""%>
          <%end%>
        <%end%>
        <strong>]</strong>
    <% end %>
    </div>
    <% if signed_in? && user_allowed_to_edit(current_user, bookmark)  %>
      <div class="item_links">
        <%= link_to t(:edit), edit_bookmark_path(bookmark) %>
        <%= link_to(t(:delete),  bookmark, :method => :delete, :confirm => "Are you sure?") %>
      </div>
    <%end%>
  </div>
</div>

app/views/bookmarks/_bookmarks.html.erb
<% bookmarks.each do |b| %>
  <%= render "bookmarks/bookmark", :locals=>{:bookmark=>b, :public_only=>public_only} %>    
<%end%>
<%= will_paginate bookmarks %>

app/views/bookmarks/_bookmarks_with_tags.html.erb
<div id="tags_wrapper">
  <%= render :partial=>"bookmarks/tag",:collection=>tags, :locals=>{:public_only=>public_only} %>
</div>
<div id="bookmarks_wrapper">
  <div id="bookmarks">  
    <%= render :partial=>"bookmarks/bookmark", :collection=>bookmarks, :locals=>{:public_only=>public_only} %>
    <%= will_paginate bookmarks %>
  </div>
</div>
<div class="clear"></div>

app/views/bookmarks/_bookmarks_without_tags.html.erb
<div id="bookmarks_wrapper">
  <div id="bookmarks">  
    <%= render :partial=>"bookmarks/bookmark", :collection=>bookmarks, :locals=>{:public_only=>public_only} %>
    <%= will_paginate bookmarks %>
  </div>
</div>

app/views/bookmarks/_form.html.erb
<%= form_for(@bookmark) do |b| %>
  <div><%= b.label :title %><%= b.text_field :title %></div>
  <div><%= b.label :url %><%= b.url_field :url %></div>
  <label for="lists">Bookmark Lists</label><br>
  <% @available_lists.each do |l| %>
    <%= check_box_tag "bookmark[list_ids][]", l.id, @bookmark.lists.detect{|d| d == l} %> <%="#{l.title}"%><br>
  <% end %>
  <div><%=b.label :tags %>
  <%= text_field_tag "tagstring", @tags, :'data-autocomplete' => users_autocomplete_tag_title_path, :'data-delimiter' => ',' %>
  <div><%= b.submit %></div>
<% end %>
<div class="clear"></div>

app/views/bookmarks/_tag.html.erb
<div class="tag_item">
  <span class="item_title">
    <% if public_only %>
      <%= link_to "#{tag.title} (#{(tag.bookmarks & @bookmarks).count})", tag_path(tag)%>
    <%else%>
      <%= link_to "#{tag.title} (#{(tag.bookmarks & @bookmarks).count})", user_tag_path(current_user,tag)%>
    <%end%>
  </span>
</div>

app/views/bookmarks/_tags.html.erb
<% if !@tags.nil? && !@tags.empty? %>
  <% @tags.each do |tag| %>
    <div class="tag_item">
      <span class="item_title">
        <% if public_only %>
          <%= link_to "#{tag.title} (#{(tag.bookmarks & @bookmarks).count})", tag_path(tag)%>
        <%else%>
          <%= link_to "#{tag.title} (#{(tag.bookmarks & @bookmarks).count})", bookmarks_tags_user_path(current_user,tag)%>
        <%end%>
      </span>
    </div>
  <%end%>
<%else%>
  no tags
<%end%>

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/edit.html.erb
<%= render "form" %>

app/views/bookmarks/index.html.erb
 <%= render :partial=>"bookmarks_with_tags", :locals=>{:public_only => true, :bookmarks=>@bookmarks, :tags=>@tags} %>

app/views/bookmarks/new.html.erb
<%= render "form" %>

app/views/bookmarks/show.html.erb
<h1>Bookmarks#show</h1>
<p>Find me in app/views/bookmarks/show.html.erb</p>

app/views/bookmarks/update.html.erb
<h1>Bookmarks#update</h1>
<p>Find me in app/views/bookmarks/update.html.erb</p>