config/routes.rb
Bookmakr::Application.routes.draw do

  get 'users/autocomplete_user_username'
  get 'users/autocomplete_tag_title'

  resources :bookmarks
  resources :tags
  
  resources :lists do
    get :share, :on=>:member
  end
  
  resources :shares 
  
  resources :users do
    get :bookmarks, :on=>:member
    get :autocomplete_tag_title_users
    get :autocomplete_user_username_users
    resources :tags, :only => :show
  end
  
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "devise/sessions"}, :path=>"account"

  root :to => 'bookmarks#index'
end

app/models/share.rb
class Share < ActiveRecord::Base
  belongs_to :user
  belongs_to :list
  
  validates :user_id, :presence => { :message => "not found" }
  # the combination of user_id and list_id is only allowed once
  validates :user_id, :uniqueness => { :scope => :list_id, :message => "already stated" }
  validate :validate_current_user
 
  def validate_current_user
    errors.add(list.user.username, ", can't share list with yourself") if user_id == list.user.id
  end
  
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
protected 
  before_filter :authenticate_user!
  
  before_filter :get_share, :only=>[:edit,:destroy,:update]

public  
  def get_share
    @share = Share.find(params[:id])
  end

  def destroy
    @share.destroy
    
    redirect_to lists_path 
  end

  def create
    @list = List.find(params[:list_id])
    
    @share = @list.shares.create(params[:share])
    users = parse_user_string(params[:user])
    
    @validUsers = []

    users.each do |u|
      user = User.find_by_username(u)
      @share.user = user
      
      if @share.valid? && !@validUsers.include?(user.username) #checks if name is stated multiple times
        @validUsers << user.username << ','
      end  
    end

    if @share.valid?
	  @share.save
      redirect_to lists_path
    else
      render :template=>"shares/new"
    end
  end
  
  def edit
    
  end

  def update
    @share.update_attributes(:write=>params[:share][:write])
    @share.save
    redirect_to lists_path
  end

  def new
    @list = List.find(params[:listid])
    @share = @list.shares.new
    @users = User.all.sort{|a,b| a.username <=> b.username }
    @users.delete(current_user)
  end
  
  #parses the user string and creates an array of users
  def parse_user_string(userstring)
    users = userstring.split(',') 
    users = users.map do |u|
      u = u.strip
    end
    return users
  end

end

app/helpers/shares_helper.rb
module SharesHelper
end

app/views/shares/_form.html.erb
<%= form_for(@share) do |f| %>
  <div><%= f.label :write%><%=f.check_box :write%></div> 
  <div><%= f.submit%></div>
<%end%>

app/views/shares/_share.html.erb
<div class="share">
  <%=share.user.username%><%=share.write == true ? " (write)": ""%>
  <div class="share_edit_links">
    <%= link_to t(:edit), edit_share_path(share) %>
    <%= link_to(t(:delete),  share, :method => :delete, :confirm => "Are you sure?") %>
  </div>
</div>

app/views/shares/destroy.html.erb
<h1>Shares#destroy</h1>
<p>Find me in app/views/shares/destroy.html.erb</p>

app/views/shares/edit.html.erb
<%= render "form" %>

app/views/shares/index.html.erb
<h1>Shares#index</h1>
<p>Find me in app/views/shares/index.html.erb</p>

app/views/shares/new.html.erb
<%= form_for(@share) do |f| %>

<% if @share.errors.full_messages.any? %>

  <ul>
    <li>
     <%= @share.errors.full_messages.first if @share.errors.any? %>
	</li>
  </ul>
<% end %>
  
  <div><%= f.label :write%><%=f.check_box :write%></div>
  <div>
  <%= f.label :users%>
  <%= text_field_tag "user",@validUsers, :'data-autocomplete' => users_autocomplete_user_username_path, :'data-delimiter' => ',' %>
  </div>
  <div><%= hidden_field_tag  'list_id', @list.id %></div>  
  <div><%= f.submit%></div>
<%end%>

app/views/shares/show.html.erb
<h1>Shares#show</h1>
<p>Find me in app/views/shares/show.html.erb</p>

app/views/shares/update.html.erb
<h1>Shares#update</h1>
<p>Find me in app/views/shares/update.html.erb</p>