config/routes.rb
Bookmakr::Application.routes.draw do

  get 'users/autocomplete_user_username'
  get 'users/autocomplete_tag_title'

  resources :bookmarks
  resources :tags
  
  resources :lists do
    get :share, :on=>:member
  end
  
  resources :shares 
  
  resources :users do
    get :bookmarks, :on=>:member
    get :autocomplete_tag_title_users
    get :autocomplete_user_username_users
    resources :tags, :only => :show
  end
  
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "devise/sessions"}, :path=>"account"

  root :to => 'bookmarks#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_default_menu.html.erb
  <ul>
    <li><%= link_to t(:home), root_path %></li>
    <li><%= link_to t(:login), new_user_session_path %></li>
    <li><%= link_to t(:register), new_user_registration_path %></li>
  </ul>

app/views/application/_user_menu.html.erb
  <ul>
    <li><%= link_to t(:home), root_path %></li>
    <li><%= link_to t(:logout), destroy_user_session_path, :method=>'delete' %></li>
    <li><%= link_to t(:my_bookmarks), bookmarks_user_path(current_user) %></li>
    <li><%= link_to t(:new_bookmark), new_bookmark_path %></li>
    <li><%= link_to t(:my_lists), lists_path %></li>
    <li><%= link_to t(:new_list), new_list_path %></li>
    <li><%= link_to t(:edit), edit_user_registration_path(current_user) %></li>
  </ul>